### ISSUE TITLE
signMetadata security setting

### ISSUE THREAD

**Issue by vbtwo31984** [hslavich/OneloginSamlBundle#10]
This setting exists in OneLogin Saml framework, but does not exist in your bundle.
I was able to easily modify and add it to configuration.php:
```
->arrayNode('security')
    ->children()
        ->booleanNode('nameIdEncrypted')->end()
        ->booleanNode('authnRequestsSigned')->end()
        ->booleanNode('logoutRequestSigned')->end()
        ->booleanNode('logoutResponseSigned')->end()
        ->booleanNode('wantMessagesSigned')->end()
        ->booleanNode('wantAssertionsSigned')->end()
        ->booleanNode('wantNameIdEncrypted')->end()
        ->booleanNode('requestedAuthnContext')->end()
        ->booleanNode('signMetadata')->end()
```

When this was added, it worked correctly. Can you please add to bundle so I don't have to keep my modified version.

**Comment by hslavich** [comment]
These settings were added in commit 07076ecba589a26b4fc5f0e061754fbeda9c0ac5. Check you are using last code.

**Comment by hslavich** [comment]
signMetadata setting added.
