### ISSUE TITLE
1.4.1 version incompatible with tag 3.3.0 of onelogin/php-saml 

### ISSUE THREAD

**Issue by leechao** [hslavich/OneloginSamlBundle#100]
Hi, 

Composer has updated the vendor "onelogin/php-saml" to the 3.3.0 version and now users are unable to connect on our website. We had to revert to the tag 3.2.1.

Seems like there is an issue with the new version that has to be fixed

**Comment by pitbulk** [comment]
Hi @leechao , 

I'm the maintainer of php-saml. 

Can you detail what issue had you experienced with 3.3.0?
I guess the SAMLResponse was rejected due a strict validation.

The main change on this release is that the plugin will set true as the default value for the [strict parameter](https://github.com/onelogin/php-saml#settings)

Be aware that [production instances MUST have strict = true](https://github.com/onelogin/php-saml#security-warning)

**Comment by a-menshchikov** [comment]
@leechao let me know if this issue is still actual, I will reopen it.
