### ISSUE TITLE
Deprecation

### ISSUE THREAD

**Issue by arturslogins** [hslavich/OneloginSamlBundle#101]
User Deprecated: Auto-injection of the container for "Hslavich\OneloginSamlBundle\Controller\SamlController" is deprecated since Symfony 4.2. 
Configure it as a service instead. 
{"exception":"[object] (ErrorException(code: 0): User Deprecated: Auto-injection of the container for \"Hslavich\\OneloginSamlBundle\\Controller\\SamlController\" is deprecated since Symfony 4.2. Configure it as a service instead. at vendor/symfony/framework-bundle/Controller/ControllerResolver.php:64)"} 

This deprecation warning comes from lib or I should, so how, reconfigure it in my symfony project?

**Comment by hslavich** [comment]
This deprecation comes from the bundle in newer versions of Symfony. 
I'll fix this soon.
Thanks

**Comment by arturslogins** [comment]
When you will release this deprecation fix?

**Comment by amalricBzh** [comment]
Hi,
Using OneloginSamlBundle last version (v1.5.0) and last Symfony 4 branch (4.4.9), I still have this issue. Please when will it be fixed ?
