### ISSUE TITLE
insert user after login

### ISSUE THREAD

**Issue by farestayari** [hslavich/OneloginSamlBundle#117]
hello @hslavich ,

i have a problem after attempt to log in, it always stuck on /saml/acs and tries to insert the user every single time to the database ,all i want to do is when it find the user it log in without creating a new user everytime , i tried with UserFactory but it didnt solve the problem

**Comment by lamine78c** [comment]
Hello,
I have the same problem.
Did you find a solution?
Thanks,

**Comment by a-menshchikov** [comment]
If you use an [Entity User Provider](https://symfony.com/doc/current/security/user_providers.html#entity-user-provider), this does not lead to inserting the user to database (but be careful with `Symfony\Component\Security\Core\User\UserProviderInterface::refreshUser` if your user class repository implements `UserProviderInterface` and be careful twice if not).

Now this bundle will try to insert the user to the database only if you setting up [the user persistence](https://github.com/hslavich/OneloginSamlBundle#persist-user-on-creation-and-saml-attributes-injection-optional).

A new user instance is created by the UserFactory in a case when `UserNotFoundException` is catched during the user loading from UserProvider. If there is no UserFactory the exception will be thrown further.
____

I close this issue now, but anyone can reopen it if need.
