### ISSUE TITLE
Make strict mode customizable in config

### ISSUE THREAD

**Issue by dialogik** [hslavich/OneloginSamlBundle#12]
On the base repository, the [settings for `strict` mode can be customized](https://github.com/onelogin/php-saml#settings). It would be good if that could be customized in this bundle, too.

By the way: If the default setting of `strict` is `false`, does this mean that it's `false` when using it with this bundle?

**Comment by hslavich** [comment]
This options should be available. Check https://github.com/hslavich/OneloginSamlBundle/blob/master/DependencyInjection/Configuration.php#L25.

I think I have to update docs.

**Comment by dialogik** [comment]
So it's simply like this? (I added the `debug` variable as well.)

    hslavich_onelogin_saml:
        debug: true|false
        strict: true|false
        idp:
            ...

**Comment by hslavich** [comment]
Yes. You can also use "%kernel.debug%"  to toggle debug between environments.
