### ISSUE TITLE
Error Symfony 5.0 

### ISSUE THREAD

**Issue by mari0theminer** [hslavich/OneloginSamlBundle#120]
when loading the route saml/login this Error shows up "Hslavich\OneloginSamlBundle\Controller\SamlController" has no container set, did you forget to define it as a service subscriber?"

Symfony-version= 5.0.5
Bundel version: dev-master

**Comment by pluk77** [comment]
You might also want to inject OneLogin\Saml2\Auth into the controller methods instead of using $this->get('onelogin_auth')

**Comment by pimjansen** [comment]
Same here, any update on this?

**Comment by mari0theminer** [comment]
@pimjansen  YES there is , you can youse my own forg https://github.com/mari0theminer/symfony_5_saml
"require": {
    "mari0theminer/symfony_5_saml": "dev-master"
}

**Comment by pimjansen** [comment]
@mari0theminer great but im not a fan for a random fork tbh. Its ok for testing but im.more curious for a stable released fix

**Comment by mari0theminer** [comment]
> @mari0theminer great but im not a fan for a random fork tbh. Its ok for testing but im.more curious for a stable released fix

neither do I.
a Pull request is already opened by  @hslavich https://github.com/hslavich/OneloginSamlBundle/pull/121

**Comment by a-menshchikov** [comment]
Problems with Symfony 5 solved.
If for some reason this issue needs to be reopened, let me know.
