### ISSUE TITLE
Symfony 5.1: Invalid array settings: sp_not_found, idp_not_found

### ISSUE THREAD

**Issue by JoostFaber** [hslavich/OneloginSamlBundle#124]
Hi,

I have tried to use this bundle with Symfony 5.1 but it looks like the settings are not loaded in Settings.php.

For Symfony 5.0 everything works fine.

Here is the configuration of the Symfony 5.1 application:

------------------------------------------------------------------------------------------------------------------------------------
hslavich_onelogin_saml:
  # Basic settings
  idp:
    #    entityId: 'http://id.example.com/saml2/idp/metadata.php'
    entityId: 'http://idp.local/simplesaml/saml2/idp/metadata.php'
    singleSignOnService:
      #      url: 'http://id.example.com/saml2/idp/SSOService.php'
      url: 'http://idp.local/simplesaml/saml2/idp/SSOService.php'
      binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
    singleLogoutService:
      #      url: 'http://idp.local/simplesaml/saml2/idp/SingleLogoutService.php'
      url: 'http://idp.local/simplesaml/saml2/idp/SingleLogoutService.php'
      binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
    x509cert: '-certificate code-'
  sp:
    #    entityId: 'http://myapp.com/app_dev.php/saml/metadata'
    entityId: 'http://samltest.local/index.php/saml/metadata'
    assertionConsumerService:
      #      url: 'http://myapp.com/app_dev.php/saml/acs'
      url: 'http://samltest.local/index.php/saml/acs'
      binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST'
    singleLogoutService:
      #      url: 'http://myapp.com/app_dev.php/saml/logout'
      url: 'http://samltest.local/index.php/saml/logout'
      binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
    privateKey: ''
  # Optional settings
  baseurl: 'http://samltest.local/saml'
  strict: true
  debug: true
  security:
    nameIdEncrypted:       false
    authnRequestsSigned:   false
    logoutRequestSigned:   false
    logoutResponseSigned:  false
    wantMessagesSigned:    false
    wantAssertionsSigned:  false
    wantNameIdEncrypted:   false
    requestedAuthnContext: true
    signMetadata: false
    wantXMLValidation: true
    signatureAlgorithm: 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256'
    digestAlgorithm: 'http://www.w3.org/2001/04/xmlenc#sha256'
  contactPerson:
    technical:
      givenName: 'Administrator'
      emailAddress: '-email-'
    support:
      givenName: 'Administrator'
      emailAddress: '-email-'
  organization:
    en:
      name: 'Example'
      displayname: 'Example'
      url: 'http://idp.local'
------------------------------------------------------------------------------------------------------------------------------------

**Comment by szabi7** [comment]
Have you found a solution?

**Comment by szabi7** [comment]
This fixed it for me in services.yaml

imports:
    - { resource: 'packages/hslavich_onelogin_saml.yml' }
