### ISSUE TITLE
Dependency on a non-existent service

### ISSUE THREAD

**Issue by dialogik** [hslavich/OneloginSamlBundle#13]
I installed and configured this bundle according to install instructions. When I try to perform console commands (e.g. `php app/console server:run` or `php app/console generate:bundle`), I get this error:

    [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]
    The service "security.authentication.provider.saml.app" has a dependency on
    a non-existent service "".

And similar when I open the app via my browser:

    ServiceNotFoundException in CheckExceptionOnInvalidReferenceBehaviorPass.php line 58:
    The service "security.authentication.provider.saml.app" has a dependency on a non-existent
    service "".

Any ideas what the problem could be?

**Comment by hslavich** [comment]
I cant reproduce this issue, could you paste your require composer settings?

**Comment by dialogik** [comment]
It's the [basic `composer.json` from the symfony/symfony-standard](https://github.com/symfony/symfony-standard/blob/2.8/composer.json) repository, extended by this line

    "hslavich/oneloginsaml-bundle": "dev-master"

**Comment by dialogik** [comment]
To give more information on this problem: I've generated a bundle with the sensio generator. See [this gist](https://gist.github.com/dialogik/2b99545704e26a029e37) in order to view all changes after installing the standard symfony.

**Comment by dialogik** [comment]
This error originally occured on Windows 7 Enterprise (x64, SP1). I just reproduced it on Ubuntu 14.04.2 (x64).

**Comment by dialogik** [comment]
Uh great, but I can't figure out: What was the problem?

**Comment by hslavich** [comment]
A bug when user factory is empty. The firewall was trying to inject a non existent user factory service.

**Comment by dialogik** [comment]
Very welcome. How come that this error occured if it's the basic configuration? Have you tested it with another config?
