### ISSUE TITLE
The controller for URI "/saml/login" is not callable: Controller "Hslavich\OneloginSamlBundle\Controller\SamlController" has required constructor arguments and does not exist in the container. Did you forget to define the controller as a service?

### ISSUE THREAD

**Issue by cilefen** [hslavich/OneloginSamlBundle#131]
This module is working after the 2.0.0 release on commit d7b34966c1b35fd0b36cbce5a80214801cb2c0b6 but the above exception occurs on master starting with commit ca5ba060909e763daa8eb1eb6afed268daea251f.

**Comment by a-menshchikov** [comment]
@cilefen hello!
This problem was fixed few days ago. Could you update to 2.1 and check it?

**Comment by cilefen** [comment]
@a-menshchikov Yes, it is working on 2.1. Thank you.
