### ISSUE TITLE
Question / What is baseurl for ?

### ISSUE THREAD

**Issue by yalefresne** [hslavich/OneloginSamlBundle#137]
Hello,

i'm using this bundle v1.5.1 with Symfony 3.4 and had some issues, i think similar to this issue #114  

I had read the onelogin php-saml doc, which says ([here](https://github.com/onelogin/php-saml#url-guessing-methods)):
> At the settings the developer will be able to set a 'baseurl' parameter that automatically will use setBaseURL to set values for setSelfProtocol, setSelfHost, setSelfPort and setBaseURLPath.

So i try to set a baseurl, but don't see effect, can someone tell me more about it ?

My problem appears on this line:  
https://github.com/hslavich/OneloginSamlBundle/blob/02ec44388cadc9037c7841eea6617be0d4277880/Security/Authentication/SamlAuthenticationSuccessHandler.php#L17
cause `$relayState` is worth 'http://myurl.com:8080/saml/login' instead of 'https://myurl.com/saml/login'. So determineTargetUrl return $relayState.  

Any help would be appreciated. :-)

Thanks for work already done on this bundle.

**Comment by trickeyone** [comment]
@yalefresne Looks like it passed through to onelogin/php-saml: https://github.com/onelogin/php-saml#settings

**Comment by a-menshchikov** [comment]
@yalefresne your problem relates to RequestContext that used by UrlGenerator::generate() method (under the hood of HttpUtils::generateUri). You can change host, port and other parts of the generated url by using according parameters (see https://symfony.com/doc/4.4/routing.html#generating-urls-in-commands).
