### ISSUE TITLE
Is possible to use behind a reverse proxy with different path?

### ISSUE THREAD

**Issue by sergiovier** [hslavich/OneloginSamlBundle#139]
Using this bundle, symfony 4.4 app behind reverse proxy (traefik) produces:

- Access to: public url: **http://url.local:9999/alias/app** 
- should redirect to **http://url.local:9999/alias/app/saml/login** 
- Instead, redirect to: **http://url.local:9999/saml/login** 

Some configs:
- reverse proxy strip path **/alias/app** 
- in sf app, baseurl: **http://url.local:9999/alias/app** is set
- in sf app, **Request::setTrustedProxies()** and **OneLogin\Saml2\Utils::setProxyVars(true);** are setted ...

Appears to be a local problem with this symfony 4.4 app setup.. any idea?

**Comment by a-menshchikov** [comment]
@sergiovier is this issue actual for you?

**Comment by sergiovier** [comment]
@a-menshchikov let me re-check this issue.

**Comment by a-menshchikov** [comment]
If this issue is still actual, reopen it.
