### ISSUE TITLE
Remove dependency on Entity Manager

### ISSUE THREAD

**Issue by Taluu** [hslavich/OneloginSamlBundle#14]
In the SamlUserProvider, you are depending (through a setter injection) on doctrine's orm `EntityManager`. I don't think it should be its role to actually persist or not the entity, neither should there be an option to do so. It should be up to the developper using it, at the appropriate place.

Because what if we are using something like an ODM or even Propel (not my case, but still a possibility) ? What if we need to control when and what we are persisting (which is my case) ?

Cheers.

**Comment by hslavich** [comment]
The persist option is totally optional. There is no real dependency on Entity Manager, note that entity manager could be null and the persist will never happen.
See `SecurityCompilerPass` and note that this is injecting entity manager only when it is defined. (https://github.com/hslavich/OneloginSamlBundle/blob/master/DependencyInjection/Compiler/SecurityCompilerPass.php)

**Comment by hslavich** [comment]
With ODM or Propel you should create your own user provider.
