### ISSUE TITLE
Problems with the new AuthenticatorManager feature of symfony 5.1 and compatibility to other bundles

### ISSUE THREAD

**Issue by pixelfantasy** [hslavich/OneloginSamlBundle#146]
Hello folks,

I am running my application on symfony 5.1 and integrated your bundle for the single-sign-on feature, which works like a charm. As there is a login-form based ldap-authentication as well, I followed the instructions of the readme.md and combined saml and form_login under one firewall. 

**security.yaml**

    security:
        enable_authenticator_manager: true

        providers:
            user_provider:
                # Loads user from user repository
                entity:
                    class: 'App\Entity\AppUser'
                    property: username

        firewalls:
            default:
                saml:
                    username_attribute: uid
                    use_attribute_friendly_name: false
                    check_path: saml_acs
                    login_path: saml_login
                    failure_path: saml_login
                    always_use_default_target_path: true

                # Traditional login form
                form_login:
                    login_path: /login
                    check_path: /login_check
                    always_use_default_target_path: true

                logout:
                    path: saml_logout

But now I have to integrate an OAuth feature for the rest api. Meanwhile I installed two different bundles, but both of them are still not compatible to the new AuthenticatorManager feature of symfony 5.1. 

**An error message occurs:**
    
    Cannot configure AuthenticatorManager as "fos_oauth" authentication does not support it, set "security.enable_authenticator_manager" to `false`.

But now I am trapped. If I set enable_authenticator_manager to false, the combined firewall will not work anymore. So I splitted it up in two firewalls. Because of my symfony 5.1 setup your bundle was installed at version 2.1.2. But now there is some weird behavior in my CustomUserFactory which implements SamlUserFactoryInterface.

With **enable_authenticator_manager** set to **true** the function createUser receives $username and $attributes as defined in the interface

    <?php

    namespace Hslavich\OneloginSamlBundle\Security\User;

    use Symfony\Component\Security\Core\User\UserInterface;

    interface SamlUserFactoryInterface
    {
        /**
         * Creates a new User object.
         */
        public function createUser($username, array $attributes = []): UserInterface;
    }

But with **enable_authenticator_manager** set to **false** the function createUser receives the token as $username and $attributes is an empty array. Are there any plans to support symfony 5.1+ with the ability to enable and disable the new security feature? Right now I dont see any other possibility to combine all those 3 features in one application than to code a workaround. My last try will be to downgrade to version 2.0.0 because this was the last state using the meanwhile renamed LegacySamlUserFactoryInterface.

**Comment by pixelfantasy** [comment]
Meanwhile I got it running by adjusting some points. With this configuration I was able to install trikoder oauth2 bundle and got it running without any errors about the authenticator_manager. Hope this helps someone :-)

    security:
        enable_authenticator_manager: false

        providers:
            user_provider:
                # if there are multiple user providers now they have to be added their matching firewall
                entity:
                    class: 'App\Entity\AppUser'
                    property: username

        firewalls:
            firewall_name:
                pattern: ^/
                # with authenticator_manager deactivated anonymous token must be enabled
                anonymous: ~
                saml:
                    username_attribute: uid
                    use_attribute_friendly_name: false
                    check_path: saml_acs
                    login_path: saml_login
                    failure_path: saml_login
                    default_target_path: app_home
                    always_use_default_target_path: true
                form_login:
                    login_path: /login
                    check_path: /login_check
                    default_target_path: app_home
                    always_use_default_target_path: true
                # not totally sure about that: the entry_point should be set when authenticator_manager is deactivated
                # because there are two active authenticators within one firewall (saml, form_login)
                guard:
                    authenticators:
                        - 'App\Security\YourGuardAuthenticator'
                    entry_point: 'App\Security\YourGuardAuthenticator'
                logout:
                    path: saml_logout
                    invalidate_session: true

    # with deactivated authenticator_manager switch PUBLIC_ACCESS back to IS_AUTHENTICATED_ANONYMOUSLY
    access_control:
        - { path: ^/saml/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/saml/metadata, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/saml, roles: IS_AUTHENTICATED_FULLY, requires_channel: https }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }

**Comment by danigv** [comment]
I guess `enable_authenticator_manager` should not be mandatory as it is an optional feature of Symfony. I tried to use LegacySamlUserFactoryInterface in my user factory but it's not possible.

**Comment by a-menshchikov** [comment]
@pixelfantasy Sorry for so late response.
There is no plans to support work with disabled new authenticator manager.
