### ISSUE TITLE
Always redirect to login when I put a role in setSamlAttributes

### ISSUE THREAD

**Issue by EduardoAcunaCoronado** [hslavich/OneloginSamlBundle#148]
I have this code:

public function setSamlAttributes(array $attributes)
{
        $this->username = $attributes['eduPersonPrincipalName'][0];
        $this->firstName = $attributes['gn'][0];
        $this->lastName = $attributes['sn'][0];
        $this->password = "-";
        $this->email = $attributes['irisMailMainAddress'][0];
        if(strcmp($attributes['eduPersonPrimaryAffiliation'][0], 'student') === 0) {
            $this->setRoles(['ROLE_STUDENT']);
        }
        else {
            $this->setRoles(['ROLE_TEACHER']);
        }    
}

And always redirect to login when the user have a role distint of ROLE_USER.

Anyone can help me?

**Comment by a-menshchikov** [comment]
@EduardoAcunaCoronado hello.
Could you show your security config (security.yaml)?

**Comment by EduardoAcunaCoronado** [comment]
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_AREA_ALL: [ROLE_AREA_LIST, ROLE_AREA_CREATE, ROLE_AREA_READ, ROLE_AREA_UPDATE, ROLE_AREA_DELETE]
        ROLE_COMPETENCY_ALL: [ROLE_COMPETENCY_LIST, ROLE_COMPETENCY_CREATE, ROLE_COMPETENCY_READ, ROLE_COMPETENCY_UPDATE, ROLE_COMPETENCY_DELETE]
        ROLE_CONFIG_ALL: [ROLE_CONFIG_LIST, ROLE_CONFIG_CREATE, ROLE_CONFIG_READ, ROLE_CONFIG_UPDATE, ROLE_CONFIG_DELETE]
        ROLE_DEGREE_ALL: [ROLE_DEGREE_LIST, ROLE_DEGREE_CREATE, ROLE_DEGREE_READ, ROLE_DEGREE_UPDATE, ROLE_DEGREE_DELETE]
        ROLE_DEPARTMENT_ALL: [ROLE_DEPARTMENT_LIST, ROLE_DEPARTMENT_CREATE, ROLE_DEPARTMENT_READ, ROLE_DEPARTMENT_UPDATE, ROLE_DEPARTMENT_DELETE]
        ROLE_GUIDE_ALL: [ROLE_GUIDE_LIST, ROLE_GUIDE_CREATE, ROLE_GUIDE_READ, ROLE_GUIDE_UPDATE, ROLE_GUIDE_DELETE, ROLE_GUIDE_PRINT]
        ROLE_METHODOLOGY_ALL: [ROLE_METHODOLOGY_LIST, ROLE_METHODOLOGY_CREATE, ROLE_METHODOLOGY_READ, ROLE_METHODOLOGY_UPDATE, ROLE_METHODOLOGY_DELETE]
        ROLE_REFERENCE_ALL: [ROLE_REFERENCE_LIST, ROLE_REFERENCE_CREATE, ROLE_REFERENCE_READ, ROLE_REFERENCE_UPDATE, ROLE_REFERENCE_DELETE]
        ROLE_REVIEW_SHEET_ALL: [ROLE_REVIEW_SHEET_LIST, ROLE_REVIEW_SHEET_CREATE, ROLE_REVIEW_SHEET_READ, ROLE_REVIEW_SHEET_UPDATE, ROLE_REVIEW_SHEET_DELETE]
        ROLE_SUBJECT_ALL: [ROLE_SUBJECT_LIST, ROLE_SUBJECT_CREATE, ROLE_SUBJECT_READ, ROLE_SUBJECT_UPDATE, ROLE_SUBJECT_DELETE]
        ROLE_CENTER_ALL: [ROLE_CENTER_LIST, ROLE_CENTER_CREATE, ROLE_CENTER_READ, ROLE_CENTER_UPDATE,ROLE_CENTER_ENABLE,ROLE_CENTER_DISABLE,]
        ROLE_TEACHER_ALL: [ROLE_TEACHER_LIST, ROLE_TEACHER_CREATE, ROLE_TEACHER_READ, ROLE_TEACHER_UPDATE, ROLE_TEACHER_DELETE]
        ROLE_USER_ALL: [ ROLE_USER_LIST, ROLE_USER_CREATE, ROLE_USER_READ, ROLE_USER_UPDATE, ROLE_USER_DELETE]


        ROLE_USER: [ ROLE_AREA_ALL, ROLE_COMPETENCY_ALL, ROLE_CONFIG_ALL, ROLE_DEGREE_ALL, ROLE_DEPARTMENT_ALL, ROLE_GUIDE_ALL, ROLE_METHODOLOGY_ALL, ROLE_REFERENCE_ALL, ROLE_REVIEW_SHEET_ALL, ROLE_SUBJECT_ALL, ROLE_TEACHER_ALL, ROLE_USER_ALL ]
        ROLE_DEGREE_RESPONSIBLE: [ ROLE_USER ]
        ROLE_DEGREE_REVIEW: [ ROLE_USER ]
        ROLE_GUIDE_COORDINATOR: [ ROLE_USER ]
        ROLE_STUDENT: [ ROLE_USER ]
        ROLE_TEACHER: [ ROLE_USER ]
        ROLE_DEPARTMENT_ADMIN: [ ROLE_USER ]
        ROLE_ADMIN: [ ROLE_TEACHER, ROLE_DEPARTMENT_ADMIN ]
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN ]

    providers:
        chain_provider:
            chain:
                providers: [in_memory, uhu_user_db, saml_provider]
        in_memory:
            memory:
                users:
                    admin: { password: UHU_20, roles: ['ROLE_SUPER_ADMIN'] } # UHU_20
        uhu_user_db:
            id: fos_user.user_provider.username
        saml_provider:
            # Basic provider instantiates a user with default roles
            saml:
                user_class: App\Entity\User
                default_roles: ['ROLE_USER']
    firewalls:
        dev:
            pattern:  ^/(_profiler|_wdt|css|js|translations)
            security: false
        main:
            pattern: .*
            context: user
            saml:
                # Match SAML attribute 'uid' with username.
                # Uses getNameId() method by default.
                username_attribute: eduPersonPrincipalName
                # Use the attribute's friendlyName instead of the name
                use_attribute_friendly_name: false
                always_use_default_target_path: true
                check_path: /saml/acs
                login_path: /saml/login
                # User factory service
                # user_factory: my_user_factory
                # Persist new user. Doctrine is required.
                persist_user: true
            provider: chain_provider
            form_login:
                login_path: /login
                use_forward: false
                check_path: /login_check
                always_use_default_target_path: true
                #failure_path:   null
            logout:
                path: /saml/logout
                target: /
            anonymous: ~

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/logout$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login_check$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/saml/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/saml/metadata, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^, roles: ROLE_USER }

**Comment by a-menshchikov** [comment]
Is your user class extends `\Hslavich\OneloginSamlBundle\Security\User\SamlUserInterface` ?

**Comment by EduardoAcunaCoronado** [comment]
Yes, I´m using Symfony 4.4

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Security\Core\User\UserInterface;
use Hslavich\OneloginSamlBundle\Security\User\SamlUserInterface;
use FOS\UserBundle\Model\User as BaseUser;


class User extends BaseUser implements UserInterface, SamlUserInterface  {

    private $eduPersonPrincipalName;
    private $eduPersonPrimaryAffiliation;

    private $firstName;
    private $lastName;
    private $phone;
}

**Comment by a-menshchikov** [comment]
Could you debug `\Hslavich\OneloginSamlBundle\Security\Authentication\Provider\SamlProvider::authenticate` and say what roles are contained into `$authenticatedToken`?

**Comment by morgan-blondellet** [comment]
So you want to disconnect the SAML user that just logged in if you can't find a role for this user right ?

I dit that by using an AuthenticationSuccessHandler that is called whenever a user successfully logs in. You can then put your logic in it to check his role and redirect to any page with a flash message if you like.

**Comment by hslavich** [comment]
The token is already created when `setSamlAttributes` is executed. You should handle new roles in the user provider, when the user is loaded.

**Comment by a-menshchikov** [comment]
@hslavich why?
If I understand correctly, the speech about the following `setSamlAttributes` call from `\Hslavich\OneloginSamlBundle\Security\Authentication\Provider\SamlProvider` (51-60 lines, 1.x branch):
```
if ($user) {
    if ($user instanceof SamlUserInterface) {
        $user->setSamlAttributes($token->getAttributes());
    }
    
    $authenticatedToken = $this->tokenFactory->createToken($user, $token->getAttributes(), $user->getRoles());
    $authenticatedToken->setAuthenticated(true);

    return $authenticatedToken;
}
```
In that case the token is created after `setRoles` called.
Or I'm missing something?

**Comment by hslavich** [comment]
Yes you are right, sorry. The token should have the right ROLES.
@EduardoAcunaCoronado How do you check for roles in your controllers? Make sure you are using `$this->isGranted('ROLE_USER')` and you are not looking up roles in the user object.

**Comment by EduardoAcunaCoronado** [comment]
I have another error now. I will close this issue. 

Thank you.
