### ISSUE TITLE
You cannot refresh a user from the EntityUserProvider that does not contain an identifier. The user object has to be serialized with its own identifier mapped by Doctrine.

### ISSUE THREAD

**Issue by EduardoAcunaCoronado** [hslavich/OneloginSamlBundle#149]
I have this error when I do a login.

**Comment by a-menshchikov** [comment]
@EduardoAcunaCoronado give more details, please.
Show the code where you declare the user identifier and security.yml. Are you get this error exactly on login request, or on redirect after login action?

**Comment by EduardoAcunaCoronado** [comment]
![image](https://user-images.githubusercontent.com/7659351/113696100-df15a100-96d1-11eb-8b11-54da56bf61cb.png)

Before saml_acs

security.yaml:

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512
        App\Entity\User:
            # Use native password encoder
            # This value auto-selects the best possible hashing algorithm
            # (i.e. Sodium when available).
            algorithm: sha512

    role_hierarchy:
        ROLE_AREA_ALL: [ROLE_AREA_LIST, ROLE_AREA_CREATE, ROLE_AREA_READ, ROLE_AREA_UPDATE, ROLE_AREA_DELETE]
        ROLE_COMPETENCY_ALL: [ROLE_COMPETENCY_LIST, ROLE_COMPETENCY_CREATE, ROLE_COMPETENCY_READ, ROLE_COMPETENCY_UPDATE, ROLE_COMPETENCY_DELETE]
        ROLE_CONFIG_ALL: [ROLE_CONFIG_LIST, ROLE_CONFIG_CREATE, ROLE_CONFIG_READ, ROLE_CONFIG_UPDATE, ROLE_CONFIG_DELETE]
        ROLE_DEGREE_ALL: [ROLE_DEGREE_LIST, ROLE_DEGREE_CREATE, ROLE_DEGREE_READ, ROLE_DEGREE_UPDATE, ROLE_DEGREE_DELETE]
        ROLE_DEPARTMENT_ALL: [ROLE_DEPARTMENT_LIST, ROLE_DEPARTMENT_CREATE, ROLE_DEPARTMENT_READ, ROLE_DEPARTMENT_UPDATE, ROLE_DEPARTMENT_DELETE]
        ROLE_GUIDE_ALL: [ROLE_GUIDE_LIST, ROLE_GUIDE_CREATE, ROLE_GUIDE_READ, ROLE_GUIDE_UPDATE, ROLE_GUIDE_DELETE, ROLE_GUIDE_PRINT]
        ROLE_METHODOLOGY_ALL: [ROLE_METHODOLOGY_LIST, ROLE_METHODOLOGY_CREATE, ROLE_METHODOLOGY_READ, ROLE_METHODOLOGY_UPDATE, ROLE_METHODOLOGY_DELETE]
        ROLE_REFERENCE_ALL: [ROLE_REFERENCE_LIST, ROLE_REFERENCE_CREATE, ROLE_REFERENCE_READ, ROLE_REFERENCE_UPDATE, ROLE_REFERENCE_DELETE]
        ROLE_REVIEW_SHEET_ALL: [ROLE_REVIEW_SHEET_LIST, ROLE_REVIEW_SHEET_CREATE, ROLE_REVIEW_SHEET_READ, ROLE_REVIEW_SHEET_UPDATE, ROLE_REVIEW_SHEET_DELETE]
        ROLE_SUBJECT_ALL: [ROLE_SUBJECT_LIST, ROLE_SUBJECT_CREATE, ROLE_SUBJECT_READ, ROLE_SUBJECT_UPDATE, ROLE_SUBJECT_DELETE]
        ROLE_CENTER_ALL: [ROLE_CENTER_LIST, ROLE_CENTER_CREATE, ROLE_CENTER_READ, ROLE_CENTER_UPDATE,ROLE_CENTER_ENABLE,ROLE_CENTER_DISABLE,]
        ROLE_TEACHER_ALL: [ROLE_TEACHER_LIST, ROLE_TEACHER_CREATE, ROLE_TEACHER_READ, ROLE_TEACHER_UPDATE, ROLE_TEACHER_DELETE]
        ROLE_USER_ALL: [ROLE_USER_LIST, ROLE_USER_CREATE, ROLE_USER_READ, ROLE_USER_UPDATE, ROLE_USER_DELETE,ROLE_USER_DISABLE,ROLE_USER_ENABLE]


        ROLE_USER: [ ROLE_AREA_ALL, ROLE_COMPETENCY_ALL, ROLE_CONFIG_ALL, ROLE_DEGREE_ALL, ROLE_DEPARTMENT_ALL, ROLE_GUIDE_ALL, ROLE_METHODOLOGY_ALL, ROLE_REFERENCE_ALL, ROLE_REVIEW_SHEET_ALL, ROLE_SUBJECT_ALL, ROLE_TEACHER_ALL, ROLE_USER_ALL,ROLE_CENTER_ALL ]
        ROLE_DEGREE_RESPONSIBLE: [ ROLE_USER ]
        ROLE_DEGREE_REVIEW: [ ROLE_USER ]
        ROLE_GUIDE_COORDINATOR: [ ROLE_USER ]
        ROLE_STUDENT: [ ROLE_USER ]
        ROLE_TEACHER: [ ROLE_USER ]
        ROLE_DEPARTMENT_ADMIN: [ ROLE_USER ]
        ROLE_ADMIN: [ ROLE_TEACHER, ROLE_DEPARTMENT_ADMIN ]
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN ]

    providers:
        chain_provider:
            chain:
                providers: [in_memory, app_user_provider, saml_provider]
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
        in_memory:
            memory:
                users:
                    admin: { password: UHU_20, roles: ['ROLE_SUPER_ADMIN'] } # UHU_20
        saml_provider:
            # Basic provider instantiates a user with default roles
            saml:
                user_class: App\Entity\User
                default_roles: ['ROLE_USER']
    firewalls:
        dev:
            pattern:  ^/(_profiler|_wdt|css|js|translations)
            security: false
        main:
            pattern: ^/
            anonymous: lazy
            saml:
                # Match SAML attribute 'uid' with username.
                # Uses getNameId() method by default.
                username_attribute: eduPersonPrincipalName
                # Use the attribute's friendlyName instead of the name
                use_attribute_friendly_name: false
                always_use_default_target_path: true
                check_path: /saml/acs
                login_path: /saml/login
                # User factory service
                # user_factory: my_user_factory
                # Persist new user. Doctrine is required.
                persist_user: true
            provider: chain_provider
            form_login:
                login_path: /login
                use_forward: false
                check_path: /login_check
                always_use_default_target_path: true
                #failure_path:   null
            logout:
                path: /saml/logout
                target: /

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/saml/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/saml/metadata, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/.*, role: IS_AUTHENTICATED_FULLY  }


User.php

class User implements UserInterface, SamlUserInterface, \Serializable  {


    private $id;
    private $username;
    private $usernameCanonical;
    private $email;
    private $emailCanonical;
    private $enabled;

...

**Comment by a-menshchikov** [comment]
When you use EntityUserProvider, you should specify identifier property explicitly (with `@ORM\Id` annotation e.g.).

**Comment by EduardoAcunaCoronado** [comment]
Can you give me an example, ¿please?

**Comment by a-menshchikov** [comment]
You can look for example in the [Symfony docs](https://symfony.com/doc/current/doctrine.html#creating-an-entity-class).

**Comment by EduardoAcunaCoronado** [comment]
I do this and I have the same problem.

**Comment by a-menshchikov** [comment]
Show your user class with annotations and Doctrine config, please.

**Comment by EduardoAcunaCoronado** [comment]
I use Doctrine via xml

User.orm.xml

<doctrine-mapping xmlns="http://doctrine-project.org/schemas/orm/doctrine-mapping"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://doctrine-project.org/schemas/orm/doctrine-mapping
                          https://www.doctrine-project.org/schemas/orm/doctrine-mapping.xsd">

    <entity name="App\Entity\User" table="user"
              repository-class="App\Repository\UserRepository">

        <id name="id" column="id" type="integer" >
            <generator strategy="AUTO"/>
        </id>
        <field name="username" column="username" type="string"/>
        <field name="usernameCanonical" column="username_canonical" type="string"/>
        <field name="email" column="email" type="string"/>
        <field name="emailCanonical" column="email_canonical" type="string"/>

        <field name="password" column="password" type="string"/>
        <field name="enabled" column="enabled" type="boolean"/>
        <field name="salt" column="salt" type="string" nullable="true"/>

        <field name="confirmationToken" column="confirmation_token" type="string" nullable="true"/>

        <field name="lastLogin" column="last_login" type="datetime" nullable="true"/>
        <field name="passwordRequestedAt" column="password_requested_at" type="datetime" nullable="true"/>


        <field name="firstName" column="first_name" type="string"/>
        <field name="lastName" column="last_name" type="string"/>
        <field name="roles" column="roles" type="json"/>

        <many-to-one field="department" target-entity="App\Entity\Department" inversed-by="users">
            <join-column name="department" referenced-column-name="id" on-delete="CASCADE"/>
        </many-to-one>

        <one-to-many field="locations" target-entity="App\Entity\Location" mapped-by="user">
        </one-to-many>

        <one-to-one field="responsable_departamento" target-entity="Department" mapped-by="responsable" />

        <many-to-many field="comisions" mapped-by="users" target-entity="Comision"/>

        <one-to-many field="users_guides" target-entity="User_Guide" mapped-by="users_guides" />

    </entity>
</doctrine-mapping>

**Comment by EduardoAcunaCoronado** [comment]
doctrine.yaml

doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your db driver and server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #driver: 'mysql'
        #server_version: '5.7'

        # Only needed for MySQL (ignored otherwise)
        charset: utf8mb4
        default_table_options:
            collate: utf8mb4_unicode_ci
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine'
                prefix: 'App\Entity'
                alias: App

**Comment by a-menshchikov** [comment]
You are using `persist_user: true` option for SamlListener, but this only works in conjunction with `user_factory` option. See [docs](https://github.com/hslavich/OneloginSamlBundle/tree/1.x#just-in-time-user-provisioning-optional).

**Comment by a-menshchikov** [comment]
@EduardoAcunaCoronado the problem has been solved?

**Comment by EduardoAcunaCoronado** [comment]
Yes
