### ISSUE TITLE
There is no extension able to load the configuration for "hslavich_saml_sp"

### ISSUE THREAD

**Issue by ginokok1996** [hslavich/OneloginSamlBundle#151]
Hello,

Im currently following the steps in the readme.
When adding the routing.yaml line the following error occurs:
`There is no extension able to load the configuration for "hslavich_saml_sp" (in "/srv/api/config/packages/routing.yaml"). Looked for namespace "hslavich_saml_sp", found ""framework", "sensio_framework_extra", "security", "mercure", "twig", "doctrine", "api_platform", "nelmio_cors", "web_profiler", "maker", "common_ground", "stof_doctrine_extensions", "doctrine_fixtures", "tbbc_money", "knp_markdown", "doctrine_migrations", "endroid_qr_code", "hslavich_onelogin_saml"" in /srv/api/config/packages/routing.yaml (which is loaded in resource "/srv/api/config/packages/routing.yaml").`

I'm using version 2.1.4 at the moment since my application is still on symfony 5.1.

Can it be that the way to set routing.yaml has changed since then?
And if so what should i be using for version 2.1.4.

Thanks in advance!

**Comment by LorenzoProd** [comment]
I had the same error with symfony 5.2.6.
Solved adding the code below in `app/config/routes.yaml`
``` yml
hslavich_saml_sp:
    resource: "@HslavichOneloginSamlBundle/Resources/config/routing.yml"
```

**Comment by trickeyone** [comment]
The documentation looks to not have really been updated in a while. It's definitely missing updates regarding Symfony v5+. As @LorenzoProd noted, the routing should go in Symfony v5's `config/routes.yaml` instead of the `app/config/config/yml` as indicated in the README.

**Comment by ginokok1996** [comment]
Thanks, forgot to post it here but noticed it too.
Maybe a good idea for a readme update soon.
