### ISSUE TITLE
[Question] Deprecation warnings

### ISSUE THREAD

**Issue by trickeyone** [hslavich/OneloginSamlBundle#154]
I'm currently using v2.2.1. About a week ago, I spent about 2-3 days trying to find out why the authentication workflow seemed to be a bit off. A number of the classes in this package are flagged as `deprecated since 2.1` but are still being widely used by the package itself. I was expecting the authentication would be done by the `SamlAuthenticator` but it appears that it's never utilized except in the services definition. When I was troubleshooting issues with OneLogin, I kept noticing that the logged exceptions were always stemming from the `SamlListener`. No matter what, the `SamlAuthenticator` was never being hit. I mostly knew this because I added some debugging logger messages that I never saw logged.

So, my question is, why are these being flagged as deprecated services when they are still the actual backbone for the authentication?

**Comment by a-menshchikov** [comment]
@trickeyone hi.
`SamlAuthenticator` is a part of new authentication mechanism (since Symfony 5.1). To use it you should set `enable_authenticator_manager: true` in your `config/packages/security.yaml`.

Deprecated classes are not used when this setting is on.
