### ISSUE TITLE
[QUESTION] How I can buy you a beer?

### ISSUE THREAD

**Issue by TheCelavi** [hslavich/OneloginSamlBundle#157]
I want to buy you a beer. How can I do that?

**Comment by hslavich** [comment]
Hi! you can try here: https://cafecito.app/hslavich
Thank you! :)

**Comment by TheCelavi** [comment]
My bank does not allow me :( - do you have a PayPal account maybe?

**Comment by hslavich** [comment]
You can find me in paypal as hernanslavich1
or you can buy a beer to @a-menshchikov who is helping a lot to maintain this project

**Comment by a-menshchikov** [comment]
@hslavich Thank you! :+1: 
I believe that I have not yet earned this beer. In a couple of weeks, I plan to start working on a 3.0 that will be based on SF6 (and PHP 8), and when it will be released... =)

**Comment by TheCelavi** [comment]
GOD DAMN! This bundle really helped me to deliver SAML integration in a couple of days, I really appreciate your work. If you have any idea how to pay you back, let me know.

![image](https://user-images.githubusercontent.com/410738/120226335-46218300-c247-11eb-902a-d2b887be9c09.png)
