### ISSUE TITLE
Use NameID as Username

### ISSUE THREAD

**Issue by alberto-coolshop** [hslavich/OneloginSamlBundle#17]
I'm using a fork of this bundle to be able to pack it into on of our app.
I noticed that is not possible to use the NameId as username to check authentication.

The solution we adopted is a simple assumption: https://github.com/Coolshop/OneloginSamlBundle/blob/master/Security/Firewall/SamlListener.php#L51-L55
if username_attribute is equal to 'uid' than into the authentication Listener the nameId is used instead of one of the attributes.

Do you think that it could be a solution?

**Comment by hslavich** [comment]
Yeah that could work, but I think that NameID should be used by default as username (when 'username_attribute' is not set).
I will fix this asap.
Thank you.

**Comment by alberto-coolshop** [comment]
Yes, it makes more sense ;)

**Comment by hslavich** [comment]
Closes in https://github.com/hslavich/OneloginSamlBundle/commit/3ba5226071547996756a54090f7b79a885b37ef9
