### ISSUE TITLE
Can we get a Token Factory back?

### ISSUE THREAD

**Issue by pluk77** [hslavich/OneloginSamlBundle#181]
I am using the new SamlAuthenticator in Symfony 5.3 which works wonderful, but I see that the token factory has been removed from the new code.

In legacy mode, we could provide our custom token factory which allowed us to take more control over what went into the token. For example, I would like to use one of the token attributes to determine the users roles, which could be done if we can inject our own token factory.

Are you open to a PR for bringing a token factory back? 

```php
namespace Hslavich\OneloginSamlBundle\Security\Http\Authenticator\Token

interface SamlTokenFactoryInterface
{
    /**
     * Creates a new SAML Token object.
     *
     * @param SamlPassportInterface $passport
     * @param string $firewallName
     *
     * @return SamlTokenInterface
     */
    public function createToken(SamlPassportInterface $passport, string $firewallName): SamlTokenInterface;
    
}

class SamlTokenFactory implements SamlTokenFactoryInterface
{
    public function createToken(SamlPassportInterface $passport, string $firewallName): SamlTokenInterface
    {        
        return new SamlToken($passport->getUser(), $firewallName, $passport->getUser()->getRoles(), $passport->getAttributes());
    }

}
```

SamlAuthenticator to receive a tokenFactory as a setting via secutity.yaml with the SamlTokenFactory as the default:
```php
public function createAuthenticatedToken(PassportInterface $passport, string $firewallName): TokenInterface
    {
        if (!$passport instanceof SamlPassportInterface) {
            throw new LogicException(sprintf('Passport should be an instance of "%s".', SamlPassportInterface::class));
        }

        return $this->tokenFactory->createToken($passport, $firewallName);
    }
```

**Comment by a-menshchikov** [comment]
Hello Marcel.
You don't need TokenFactory for this purpose. You have at least 2 ways to achieve it:
- make [custom UserFactory](https://github.com/hslavich/OneloginSamlBundle#just-in-time-user-provisioning-optional);
- if your User class implements our SamlUserInterface, you can set user roles during the setSamlAttributes() method call.

If these solutions don't work for you, please describe your case more.

**Comment by pluk77** [comment]
The problem I have with using a custom UserFactory, is that the factory does not get the token attributes when retrieving the user by identifier. Our users come from a database, where the roles are also stored.

```php
$user = $this->userProvider->loadUserByIdentifier($identifier);
```

The problem with the setSamlAttributes() is that it is called directly on the user entity, which means I can not inject other services used when determining the additional roles. eg I need the entity manager registry, which I really do not want to inject into the user entity constructor and use the entity as a service.

```php
$user->setSamlAttributes($attributes);
```

Perhaps I am overlooking something?

Here is the token factory I created. The roles are assigned to a user as well as a facility and when users log in, they have to select one of their assigned facilities (In the IDP, so it is passed to the application via the SML token attribute seeAlso).

When retrieving the roles for a user, we combine the roles assigned to the facility the user choose during login with those assigned to the user, so a user inherits permissions from the location they are working at (this is used to switch functionality on/off depending on where the user is working at).

The additional attributes (like facility name) set in the token are used in the UI so we can retrieve the location name, id and uuid directly from the token instead of having to retrieve the facility entity on every request.

If for whatever reason the attribute in the saml token is not set or can not be used to retrieve the facility, or the application does not have this facility in its database, we do not give the user any permissions as it means he is not allowed touse that facility in this specific application.

```php
public function __construct(ManagerRegistry $registry, $facilityProperty = 'id')
    {
        $this->registry = $registry;
        $this->facilityProperty = $facilityProperty;
    }
    
    public function createToken(SamlPassportInterface $passport, string $firewallName): SamlTokenInterface
    {        
        $attributes = $passport->getAttributes();
        if(isset($attributes['seeAlso'][0])) {
            $repository = $this->registry->getManagerForClass(Facility::class)->getRepository(Facility::class);
            $facility = $repository->findOneBy(array($this->facilityProperty => $attributes['seeAlso'][0]));
            
            if($facility) {
                $attributes[self::ATTRIBUTE_FACILITY_NAME] = $facility->__toString();
                $attributes[self::ATTRIBUTE_FACILITY_ID] = $facility->getId();
                $attributes[self::ATTRIBUTE_FACILITY_UUID] = $facility->getUuid();
            
                return new SamlToken($passport->getUser(), $firewallName, $passport->getUser()->getRoles($facility->getId()), $attributes);
            } 
        } 
        
        return new SamlToken($passport->getUser(), $firewallName, [], $attributes);
    }
```

**Comment by pluk77** [comment]
I did consider those options as well, but it does not seem to be that easy, especially when trying keep the ability to configure a custom Authenticator via options in security.yaml while maintaining the rest of your library and code.

A few lines of code in your library would solve my problem completely and could benefit others as well.

What is your biggest reservation with implementing a tokenFactory? It will add additional customization without much overhead. I will supply you the PR, so it should not take too much of your time.

**Comment by a-menshchikov** [comment]
I try to follow Occam's Razor principle in this case and don't to add any things without certain necessary.
Let's try to figure out with existing ways. There is one else that you can use: make UserModifiedEvent listener and set roles by it according the attributes were set in setSamlAttributes method. This approach definitely easier that custom Authenticator.

**Comment by a-menshchikov** [comment]
CheckPassportEvent — is really good solution, I've absolutely forgotten about it. But I don't understand what's wrong with Passport and why you need setAttributes method.

**Comment by a-menshchikov** [comment]
Now it's clear, thank you.
To solve our problem we need the only getAttributes method in base Passport class. Attributes passed into our SamlPassport constructor we can iterate as key:value and pass into setAttribute.

**Comment by pluk77** [comment]
I thought about that and tested it as well, but as we can achieve the same
result it does not make sense to make our life's more complicated than
necessary so rather have the setAttributes() as well. On top of that it
would allow for the clearing of all attributes in a subscriber by passing
an empty array, although I do not need that functionality (yet) . Let's see
if my PR gets accepted and take it from there. One way or another we will
find a solution...
