### ISSUE TITLE
Login failed page

### ISSUE THREAD

**Issue by alberto-coolshop** [hslavich/OneloginSamlBundle#19]
We noticed that there is no "login-failed" page. The problem is that when a user correctly authenticate into the idp but it's not present into the application database, because in my case the root of the application is behind firewall, except for login and metadata route. In this situation user cannot authenticate, is redirect to root, go back to idp where is already authenticated an returns to my application, looping until the idp returns an error for too many attempt.

Do you think is best to implement a path be configurable from security.yml? Do you think that should be implemented an authentication exception listener?

I'm working on it, so i'm interested in your opinion, so maybe i could do a pull request if you like...

**Comment by hslavich** [comment]
Try setting 'failure_path' with a non secured route. 
Then in the controller you can get the authentication errors:
```
$authenticationUtils = $this->get('security.authentication_utils');
$error = $authenticationUtils->getLastAuthenticationError();
$lastUsername = $authenticationUtils->getLastUsername();
```

Please tell if this work for you. Maybe the bundle should provide  a default error page with this logic.

**Comment by alberto-coolshop** [comment]
Yes it worked... but I don't get the $lastUsername
