### ISSUE TITLE
bug on php-saml onelogin dependence

### ISSUE THREAD

**Issue by pitbulk** [hslavich/OneloginSamlBundle#2]
https://github.com/hslavich/OneloginSamlBundle/blob/master/composer.json#L15

replace
 "onelogin/php-saml": "master-dev"
by
 "onelogin/php-saml": "dev-master"

**Comment by pitbulk** [comment]
Thanks, remember to update the README too

**Comment by pitbulk** [comment]
Remember to update packagist ;)

**Comment by hslavich** [comment]
That should be handled by web hook. I'll check it.
