### ISSUE TITLE
Add support for "wantNameId" and "lowercaseUrlencoding" security options

### ISSUE THREAD

**Issue by VincentClair** [hslavich/OneloginSamlBundle#27]
Hello,

Please add those two new options in config bundle:
 - wantNameId https://github.com/onelogin/php-saml/commit/9a1cec3391f0979c16cef0000ed95d6c5865240a
 - lowercaseUrlencoding (supported in a future release) https://github.com/onelogin/php-saml/commit/3738c11947b80f0f39cede18164afb052c355148

Thank you

**Comment by VincentClair** [comment]
Just as a reminder: it seems that "wantAssertionsEncrypted" option will come soon too.

**Comment by tlesne** [comment]
Hello,
There is also the attributeConsumingService node in the Service Point configuration https://github.com/onelogin/php-saml/commit/76084539d29670a6380fe1c5e9fc8175f3548f3f

**Comment by tlesne** [comment]
I just made a PR for these additions #28

**Comment by hslavich** [comment]
Merged.
