### ISSUE TITLE
Is sessionIndex supported ?

### ISSUE THREAD

**Issue by VincentClair** [hslavich/OneloginSamlBundle#29]
Hi,

I don't see the support of "sessionIndex".
It seems that the instruction `$this->samlAuth->logout(null, array(), $token->getUsername());` does not take care of it in "SamlLogoutHandler". I need it for ADFS.

Thanks for your help,

**Comment by VincentClair** [comment]
I made a PR https://github.com/hslavich/OneloginSamlBundle/pull/30 to support this.

**Comment by hslavich** [comment]
Merged.
