### ISSUE TITLE
[Question] Publication on packagist?

### ISSUE THREAD

**Issue by tlesne** [hslavich/OneloginSamlBundle#34]
Hello,
Do you have any plan to publish your package on packagist?
Thomas

**Comment by pitbulk** [comment]
Is already published..
https://packagist.org/packages/hslavich/oneloginsaml-bundle

**Comment by tlesne** [comment]
Woops, indeed.

Nevertheless is it planned to release a new version on packagist with the last evolutions?
Sorry for the first dump question ...

**Comment by hslavich** [comment]
A new version was released.
