### ISSUE TITLE
Initialise roles in user before use it in provider

### ISSUE THREAD

**Issue by Preovaleo** [hslavich/OneloginSamlBundle#35]
Hello,

I think there is a problem in the [provider](https://github.com/hslavich/OneloginSamlBundle/blob/master/Security/Authentication/Provider/SamlProvider.php#L52)
I think you use the user roles before initialise them on line [56](https://github.com/hslavich/OneloginSamlBundle/blob/master/Security/Authentication/Provider/SamlProvider.php#L56).

Is it possible to initialise an user before because it's my idp which send roles to this bundle.

Regards

**Comment by Preovaleo** [comment]
i think we can do like this 
`    public function authenticate(TokenInterface $token)
    {
        $user = $this->retrieveUser($token);

        if ($user) {
            if ($user instanceof SamlUserInterface) {
                $user->setSamlAttributes($token->getAttributes());
            }

            $authenticatedToken = $this->tokenFactory->createToken($user, $token->getAttributes(), $user->getRoles());
            $authenticatedToken->setAuthenticated(true);

            return $authenticatedToken;
        }

        throw new AuthenticationException('The authentication failed.');
    }`

**Comment by hslavich** [comment]
Hi, it's true, there was an issue if you need to generate roles based on saml attributes.
