### ISSUE TITLE
Multiple login methods, how to set default?

### ISSUE THREAD

**Issue by riyunoa** [hslavich/OneloginSamlBundle#39]
So we've got multiple authentication methods for our site - SAML and normal form login. How do we set saml to be the default? Currently, when a user is not logged in and accesses the site, they're redirected to the form login page. 

    firewalls:
        app:
            pattern:    ^/
            anonymous: true
            saml:
                check_path: /saml_consume.php
                login_path: /saml/login
                user_factory: sonicwall_user_factory
                persist_user: true
                use_referer: true
            form_login:
                login_path: login
                check_path: login
                always_use_default_target_path: true

**Comment by hslavich** [comment]
Hi @riyunoa, have you solved your issue? I'm not sure if the order of firewalls can be configured

**Comment by bpironet** [comment]
I have the exact same issue. Did you find a solution ?

**Comment by DavidGonzalezGutierrez** [comment]
https://stackoverflow.com/questions/44817785/symfony-3-multiple-login-methods-how-to-set-default
