### ISSUE TITLE
getLastLoginError not found

### ISSUE THREAD

**Issue by pitbulk** [hslavich/OneloginSamlBundle#4]
You are using getLastLoginError method that does not exists
https://github.com/hslavich/OneloginSamlBundle/blob/master/Security/Firewall/SamlListener.php#L37

use instead [getLastErrorReason](https://github.com/hslavich/OneloginSamlBundle/blob/master/Security/Firewall/SamlListener.php#L37)

**Comment by hslavich** [comment]
Solved in #7
