### ISSUE TITLE
Set roles based on admin user list in parameters?

### ISSUE THREAD

**Issue by zorfling** [hslavich/OneloginSamlBundle#41]
Hey,

I'm trying to set roles based on if the user is in a list of usernames in parameters.yml.
eg. if they're in this list, they're ROLE_ADMIN, otherwise fall back to default.

Is this possible, can you help point me in the right direction?

I guess I need to make my own version of SamlUserProvider and pass the adminUserList along with $username and $defaultRoles or something similar? 

But if you've got a better way I'm keen to hear it!

Thanks!

**Comment by hslavich** [comment]
Hi @zorfling, you have to make your own user provider. In _loadUserByUsername_ method you can search if the user is in the list.

**Comment by zorfling** [comment]
Thanks @hslavich, that's exactly what I ended up with.
