### ISSUE TITLE
How can we execute a PostMethod

### ISSUE THREAD

**Issue by manuclavier** [hslavich/OneloginSamlBundle#42]
Hi,

Is this possible to implement OneloginSamlBundle with POST method and not in GET method ?

This is not worrking :
idp:
singleSignOnService:
binding: 'urn:Oasis:names:tc:SAML:2.0:bindings:HTTP-POST'
# binding: 'urn:Oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'

How can we use your module in POST and not in redirect please ?

Regards,

Emmanuel

**Comment by hslavich** [comment]
Hi, according to Onelogin documentation, the library supports only HTTP-Redirect for singleSignOnService.
You can check this in https://github.com/onelogin/php-saml docs
