### ISSUE TITLE
Stuck in a loop when trying to log in

### ISSUE THREAD

**Issue by marvoh** [hslavich/OneloginSamlBundle#43]
I've implemented this bundle with Azure AD as the IDP.

When I access the login path on my app, the browser is stuck in a circular loop between Azure AD and my APP which I've not been able to decipher.

Here are my configurations:

_config.yml_

    hslavich_onelogin_saml:
    # Basic settings
    idp:
        entityId: 'https://login.microsoftonline.com/azure_app_id/saml2'
        singleSignOnService:
            url: 'https://login.microsoftonline.com/azure_app_id/saml2'
            binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
        singleLogoutService:
            url: 'https://login.microsoftonline.com/azure_app_id/saml2'
            binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
        x509cert: '%kernel.project_dir%/src/AppBundle/Resources/config/AzureCert.cer'
    sp:
        entityId: 'https://myapp.com/saml/meta'
        assertionConsumerService:
            url: 'https://myapp.com/saml/acs'
            binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST'
        singleLogoutService:
            url: 'https://myapp.com/saml/logout'
            binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'

_Azure AD configuration_

    Identifier(EntityId): https://myapp.com/saml/meta
    Reply URL (ACS): https://myapp.com/saml/acs

**Comment by hslavich** [comment]
Hi, this can happen due to invalid cert configuration. Look  in application logs for error messages in log in process.
