### ISSUE TITLE
Make this bundle compatible with symfony4

### ISSUE THREAD

**Issue by deromemont** [hslavich/OneloginSamlBundle#48]
https://symfony.com/blog/helping-prepare-for-symfony-4-bundle-support

**Comment by hslavich** [comment]
Hi, It is working with symfony4, use `dev-master` branch

**Comment by MedKhachira** [comment]
Hello, 
I use Symfony 4.2 and i have this error : 

Not Found
The requested URL /my_project_sf4/public/saml/login was not found on this server.

Any help please! 
I added : routes\hslavich_onelogin_saml.yaml
config\packages\hslavich_onelogin_saml.yaml
And i changed security.yaml like in bundle description.

![image](https://user-images.githubusercontent.com/3090574/52510446-3efc8400-2bfc-11e9-9eb2-74b5686116aa.png)
