### ISSUE TITLE
How is saml_provider default_roles supposed to be used?

### ISSUE THREAD

**Issue by nreynis** [hslavich/OneloginSamlBundle#49]
Hi,
it's not clear to me how the option `default_roles` is supposed to be working.

If I try to connect with an user and it's `getRoles` method returns `null`, the SamlTokenFactory will throw with this error:
```
Type error: Argument 3 passed to
Hslavich\OneloginSamlBundle\Security\Authentication\Token\SamlTokenFactory::createToken()
must be of the type array, null given,
called in /vendor/hslavich/oneloginsaml-bundle/Security/Authentication/Provider/SamlProvider.php
on line 56
```
If I force `getRoles` to return an empty array instead of null, I can connect but I've got no role at all.

Either way I can't manage to provide a `default_role` to my user.
Is this a bug or am I misunderstanding this option purpose ?

**Comment by nreynis** [comment]
Okay, I've found what was missing. The User class should implement a custom constructor:
```
public function __construct($username, array $roles)
{
    $this->username = $username;
    $this->roles = $roles;
}
```

You should document this, there is no clue anywhere that this is a requirement.

**Comment by nreynis** [comment]
Even though `SamlUserProvider` requires this constructor to work properly, `SamlUserFactory` does not use it!

SamlUserProvider:
https://github.com/hslavich/OneloginSamlBundle/blob/master/Security/User/SamlUserProvider.php

SamlUserFactory:
https://github.com/hslavich/OneloginSamlBundle/blob/master/Security/User/SamlUserFactory.php

In order to be compatible with both you need to make the arguments nullable:
```
public function __construct(?string $username, ?array $roles)
{
    $this->username = $username;
    $this->roles = $roles;
}
```

**Comment by hslavich** [comment]
Hi,
`default_roles` is a user provider setting that will be in the token when the user is logged in. You should set at least one role or the authentication will not work properly.
There is no `setUsername/setRoles` in the symfony `UserInterface`, so there is no safe way to instantiate user and set this values. It used to be a common practice to set this values in the constructor.
You are right this might be an issue that I should write in the docs. I will try to find a better way to deal with this issue.
As the you said, you need that constructor at the moment and It should work fine. Check this user class: https://github.com/hslavich/OneloginSamlBundle/blob/master/Tests/TestUser.php

Thanks
