### ISSUE TITLE
PHP 7.2 Compatibility

### ISSUE THREAD

**Issue by articque** [hslavich/OneloginSamlBundle#52]
Your library seems to be incompatible with PHP 7.2 (because of onelogin/php-saml dependency).

To solve the problem, your library needs to use the 3.0.0.x-dev version of onelogin/php-saml (the problem comes from mcrypt, deprecated in 7.1 and removed in 7.2)

**Comment by nreynis** [comment]
You can work around the issue by issung a compatibility polyfill.
Add this in your composer.json:

```json
  "require" : {
    "phpseclib/mcrypt_compat": "^1.0"
  },
  "provide": {
    "ext-mcrypt": "*"
  }
```

**Comment by articque** [comment]
Thanks a lot ! it works.

I already had mcrypt_compat in my "require" parameter but i didn't know the "provide" parameter in composer.json :)
