### ISSUE TITLE
requestedAuthnContext should accept arrays also

### ISSUE THREAD

**Issue by salahm** [hslavich/OneloginSamlBundle#59]
Hi,

According to : https://github.com/onelogin/php-saml/blob/f13c9f3ed0e0492ff938a0af0fa8270a95a9b404/lib/Saml2/AuthnRequest.php#L102-L115 

It looks like the `requestedAuthnContext` can be : 
* true
* false
* Array

The array let users customize `saml:AuthnContextClassRef` node value.

**Comment by Lctrs** [comment]
Fixed in #68 .
