### ISSUE TITLE
Support security settings

### ISSUE THREAD

**Issue by pitbulk** [hslavich/OneloginSamlBundle#6]
Right now at the config.yml we support settings for the idp and the sp, but the advanced settings are also required in a normal SAML integration, the ones related to the 'security' array:
* 'nameIdEncrypted'
* 'authnRequestsSigned'
* 'logoutRequestSigned'
* 'logoutResponseSigned'
* 'wantMessagesSigned'
* 'wantAssertionsSigned'
* 'wantNameIdEncrypted'

See that implementation: https://github.com/pitbulk/OneloginSamlBundle/commit/07076ecba589a26b4fc5f0e061754fbeda9c0ac5

**Comment by hslavich** [comment]
Solved in #7
