### ISSUE TITLE
problem to save the user in database with multiple orm

### ISSUE THREAD

**Issue by kingramizy** [hslavich/OneloginSamlBundle#62]
for my project I use two databases, and I would like to save the user who connects in the database which is not by default

I would like to save my user in "grandparc"
config.yml
`    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                    PDFRecrutementBundle: ~
            grandparc:
                auto_mapping: true
                connection: grandparc
                mappings:
                    PDFGrandParcBundle: ~`

security.yml
`        user_provider:
             entity:
                class: PDF\GrandParcBundle\Entity\Personnel
                property: sAMAccountName
                manager_name: grandparc`

do you have an idea ?

**Comment by hslavich** [comment]
Hi, this plugin uses default entity manager and can't be configured currently. I should add a config to set the manager. 
I'm tagging this as a posible feature
