### ISSUE TITLE
NameIDFormat is changed to NameIDPolicy

### ISSUE THREAD

**Issue by Vinq-it-JV** [hslavich/OneloginSamlBundle#63]
The NameIDFormat tag is no longer supported in SimpleSAMLphp V 1.15, it is replaced by NameIDPolicy. Is this something you plan to change?

Now I have to edit the files in de the **vendor** dir Configuration.php which will be altered after a composer update.

Cheers.

**Comment by hslavich** [comment]
Can you paste the changes you needed to make?
