### ISSUE TITLE
After authentication, my User entity is null

### ISSUE THREAD

**Issue by psa-ademe** [hslavich/OneloginSamlBundle#66]
Hello everyone,
I am using this Bundle but we have an issue, It seems that the SAMLlistener is not launched.
In the acs action, when I debug the User object it's null. I tried again the factory, have the same result.
Help please.

**Comment by llaville** [comment]
@psa-ademe Hello, I used it myself this last days, and I found a solution. I don't know if it's the recommanded / best practice, so I'll explain it.

In your User Entity, I've implemented the `Hslavich\OneloginSamlBundle\Security\User\SamlUserInterface`.

Here is an example : 

```
    public function setSamlAttributes(array $attributes)
    {
        $this->setUsername($attributes['uid'][0]);
        $this->setEmail($attributes['mail'][0]);
        $this->setEnabled(true);
        $this->setPassword('notused');
        $this->setRoles($attributes['roles']);
    }
```
Hope it will help !
