### ISSUE TITLE
Class App\Entity\User contains 5 abstract methods and must therefore be declared abstract

### ISSUE THREAD

**Issue by Frankniesten** [hslavich/OneloginSamlBundle#74]
Hi,

I've installed and configured the OneloginSamlBundle on Symfony 4.2.
It's possible to authenticate succesvol against the IdP but after that I get the following error:

    Class App\Entity\User contains 5 abstract methods and must therefore be declared abstract or implement the remaining methods (Symfony\Component\Security\Core\User\UserInterface::getRoles, Symfony\Component\Security\Core\User\UserInterface::getPassword, Symfony\Component\Security\Core\User\UserInterface::getSalt, ...)

Has this something to do with Symfony 4.2

Thanks!

**Comment by LazerTiberius** [comment]
Do you have implemented a User Class? App/Entity/Class does not look like you has done this step. If not so, can you post your UserClass implementation?
