### ISSUE TITLE
baseurl in config

### ISSUE THREAD

**Issue by ajstevens** [hslavich/OneloginSamlBundle#75]
Hi, 
Not all options in OneLogin are exposed via the bundle config. I added **'baseurl'** which makes the bundle work behind for instance a reverse proxy.

https://github.com/onelogin/php-saml
`
// Set a BaseURL to be used instead of try to guess
// the BaseURL of the view that process the SAML Message.
// Ex http://sp.example.com/
//    http://example.com/sp/
    'baseurl' => null,
`
Regards, 

Albert-Jan

**Comment by szabogyula** [comment]
merged in #78 pull request, thank you @hslavich
