### ISSUE TITLE
SF4 version

### ISSUE THREAD

**Issue by vichenze** [hslavich/OneloginSamlBundle#82]
Hello !

Is it planned to update the bundle for SF4 compatibility ? 
There are some deprecations like the use of `Controller` instead of `AbstractController`.

Thank you

**Comment by Livda** [comment]
The deprecations are fixed in #81 and #80. When thoses PR will be merged and a new version will be out, your issues will be gone !

**Comment by vichenze** [comment]
Ok, thank you !
