### ISSUE TITLE
Artifacts support?

### ISSUE THREAD

**Issue by newradius** [hslavich/OneloginSamlBundle#84]
The bundle offers artifacts support?

**Comment by hslavich** [comment]
Sorry, what do you mean with artifacts?

**Comment by newradius** [comment]
@hslavich I mean if it supports flows like SP-Initiated SSO - Artifact - Artifact. Something like this: https://docs.pingidentity.com/bundle/pf_sm_supportedStandards_pf83/page/task/spInitiatedSsoRedirectArtifact.html

**Comment by pitbulk** [comment]
The plugin depends on php-saml that does not support Artifact binding.

**Comment by newradius** [comment]
@pitbulk okay, thank you. I'll close this.
