### ISSUE TITLE
Symfony 4.2 compatibility?

### ISSUE THREAD

**Issue by MedKhachira** [hslavich/OneloginSamlBundle#85]
Hello,
I use Symfony 4.2 and i have this error after / because it's a secure area:

Not Found
The requested URL /my_project_sf4/public/saml/login was not found on this server.

Any help please!
I added : routes\hslavich_onelogin_saml.yaml
config\packages\hslavich_onelogin_saml.yaml
And i changed security.yaml like in bundle description.

![image](https://user-images.githubusercontent.com/3090574/52510446-3efc8400-2bfc-11e9-9eb2-74b5686116aa.png)

**Comment by hslavich** [comment]
Hi, are you sure that the error is thrown by symfony and not by the web server?

**Comment by MedKhachira** [comment]
Hi hslavich, i miss the Front Controller index.php now it's OK with this URL = my_project_sf4/public/index.php/saml/login redirect me to IDP but how Syfmony 4 don't add index.php automatically by default. I have another question in my project i need to create an API for SAML authentification how i can do that with SAMLOneLoginBundle? thanks in advance.
