### ISSUE TITLE
Attempted to call an undefined method named "getRootNode" of class "Symfony\Component\Config\Definition\Builder\TreeBuilder".

### ISSUE THREAD

**Issue by MedKhachira** [hslavich/OneloginSamlBundle#87]
Hello,

I think that the dev-master version of bundle is not compatible with Symfony 3.4 (i use 3.4.22), this file :  symfony/src/Symfony/Component/Config/Definition/Builder/TreeBuilder.php in Symfony 4.2 only it contains the function **getRootNode**  but in Symfony 3.4.22 i didn't found this function. Any one had the same problem? Thanks.

**Comment by hslavich** [comment]
It should be fixed.
