### ISSUE TITLE
security.ERROR: The response was received at http://domain/app.php/acs instead of http://domain/app.php/saml/acs

### ISSUE THREAD

**Issue by MedKhachira** [hslavich/OneloginSamlBundle#88]
Hello,

I have this issue : 
security.ERROR: The response was received at http://domain/app.php/acs instead of http://domain/app.php/saml/acs

security.INFO: Authentication request failed. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AuthenticationException(code: 0): The response was received at security.ERROR: The response was received at http://domain/app.php/acs instead of http://domain/app.php/saml/acs  at /vendor/hslavich/oneloginsaml-bundle/Security/Firewall/SamlListener.php:41>>)"} [] 

Please any helps and thanks.

**Comment by Frankniesten** [comment]
I experienced the same problem. This has something to do with your x509cert or privateKey. Set the strict config option to false (not recommended for production).

**Comment by MedKhachira** [comment]
Hi Frankniesten,

Thank you for your response, i test my solution in staging and soon it will be in prod, so i look for the reason that make ACS URL not the good. I had a success response from IDP with status success, but Symfony (oneloginbundle) can't parse the SAML XML Response.

**Comment by zaximus84** [comment]
This appears to be an issue with the onelogin/php-saml package (required by this bundle). See details here: https://github.com/onelogin/php-saml/issues/249

It could potentially be fixed in the hslavich bundle by adding a call to OneLogin\Saml2\Utils::setBaseURLPath and passing in {domain}/saml, but it's definitely a bug in the onelogin/php-saml package.

Personally, I'll be patching OneLogin\Saml2\Utils in my local installation to fix it.

**Comment by sanojv-EY** [comment]
> This appears to be an issue with the onelogin/php-saml package (required by this bundle). See details here: [SAML-Toolkits/php-saml#249](https://github.com/SAML-Toolkits/php-saml/issues/249)
> 
> It could potentially be fixed in the hslavich bundle by adding a call to OneLogin\Saml2\Utils::setBaseURLPath and passing in {domain}/saml, but it's definitely a bug in the onelogin/php-saml package.
> 
> Personally, I'll be patching OneLogin\Saml2\Utils in my local installation to fix it.

How to do this?
