### ISSUE TITLE
requestedAuthnContextComparison is not exposed

### ISSUE THREAD

**Issue by MedKhachira** [hslavich/OneloginSamlBundle#89]
Hi, please can you add this parameter to config.yml

By default this parameter  = 'exact'  ('requestedAuthnContextComparison' => 'exact'), but i want to pass 'Minimum'.

Error details : 
Fatal error: Uncaught exception 'Symfony\Component\Config\Definition\Exception\InvalidConfigurationException' with message 'Unrecognized option "requestedAuthnContextComparison" under "hslavich_saml_sp.security"'

**Comment by hslavich** [comment]
See 'requestedAuthnContext' config of onelogin/php-saml
