### ISSUE TITLE
Symfony 3.x Compatibility broken with version 1.4.1

### ISSUE THREAD

**Issue by llaville** [hslavich/OneloginSamlBundle#90]
Hello,

While all works fine on Symfony 3.4.x with release 1.4.0, I've found regression since 1.4.1, probably due to PR #80 
SF Container is not set, and `SamlController` could not retrieve `onelogin_auth` service in `loginAction`. 

Regards

**Comment by jmaheux** [comment]
Pull request #80 has broken compatibility for Symfony 2.8 by replacing Controller with
 AbstractController. I think AbstractController was added in Symfony 3.3.

**Comment by wryk** [comment]
Semver isn't respected. PR #80 should be reverted. Deprecation warnings are less problematic than a broken bundle.

Symfony 4 deprecations could be resolved again in a better way (explicit services in SamlController) later.

**Comment by L0rD59** [comment]
Hi,

Same probleme here with Symfony 3.4.18 due to this change : 

https://github.com/hslavich/OneloginSamlBundle/commit/3d5b1d74421a26f0ef63bdfdbbd7c9b0978e1e95#diff-73c2835a91afe9f45ebd35087a8a05acL10

Maybe something wrong on my own usage or configuration.

**Comment by pitbulk** [comment]
See https://github.com/hslavich/OneloginSamlBundle/issues/100#issuecomment-535691943
