### ISSUE TITLE
After login sucess oneloginsaml-bundle always redirect me to index.php/

### ISSUE THREAD

**Issue by MedKhachira** [hslavich/OneloginSamlBundle#95]
Hi everyone,

After login sucess i was redirected to default page …/index.php/ , but logically i will return to th original URL.

Thank you in advance.

**Comment by MedKhachira** [comment]
@hslavich help please : After login sucess i was redirected to default page …/index.php/ , but logically i will return to th original URL. May be it related to Relay state , RelayState=http://my_project/public/index.php/saml/login

**Comment by a-menshchikov** [comment]
See #79
