### ISSUE TITLE
main README is Symfony2 oriented

### ISSUE THREAD

**Issue by kaamui** [hslavich/OneloginSamlBundle#97]
Hello,

First of all thank you for your great work. I was wondering if the README was going to be updated to Symfony 4 architecture. 

For example, I don't know what's the equivalent of the configuration file in Symfony 4 [(Configuration Section)](https://github.com/hslavich/OneloginSamlBundle#configuration)

Is there an updated documentation somewhere ? 

Thank you.

**Comment by Livda** [comment]
It's the same for Symfony 4, you just to put the configuration in a different file in the `config` folder. For example you could have a file `config/packages/onelogin_saml_bundle.yaml` with the configuration which goes in the `app/config/config.yml` in Symfony 2. Idem for the routing elements, you can put the route configuration in a file in `config/routes/onelogin_saml_bundle.yaml`.

**Comment by kaamui** [comment]
Hello, thank you for the answer. 

So it is not the same for Symfony 4, if the expected location of the file is not the same as for Symfony 2. I would expect this change to be described for newbies like me in Symfony 4, on the main README..

Anyway, thank you.
