### ISSUE TITLE
Password reset ? 

### ISSUE THREAD

**Issue by marvin-SL** [hslavich/OneloginSamlBundle#98]
Hello,
Does  OneloginSamlBundle provide a way to reset user's password ? By sending a mail, with a link or something like that ? I didn't found my answer in the readme.
Thanks

**Comment by pitbulk** [comment]
The plugin adds SAML support what means that the user will authenticate against a 3rd party (IdP). 
So makes no sense to provide a way to execute local resets, instead the reset link to be used should be IdP's reset link.

**Comment by marvin-SL** [comment]
Thank you
